import { Submission } from "./types";

function subtractDays(date: Date, days: number): Date {
  const result = new Date(date);
  result.setDate(result.getDate() - days);
  return result;
}

const today = new Date();

export const submissions: Submission[] = [
  {
    id: "SUB-001",
    insuredName: "Global Innovations Inc.",
    lob: "General Liability",
    state: "CA",
    premium: 12500.00,
    dueDate: subtractDays(today, 5).toISOString().split('T')[0],
    underwriter: "Alice Johnson",
    status: "Overdue",
  },
  {
    id: "SUB-002",
    insuredName: "Tech Solutions Ltd.",
    lob: "Commercial Auto",
    state: "NY",
    premium: 8200.50,
    dueDate: new Date().toISOString().split('T')[0],
    underwriter: "Bob Williams",
    status: "Quoted",
  },
  {
    id: "SUB-003",
    insuredName: "Builders Co.",
    lob: "Workers Compensation",
    state: "TX",
    premium: 25000.00,
    dueDate: new Date(today.getTime() + 10 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    underwriter: "Charlie Brown",
    status: "Bound",
  },
  {
    id: "SUB-004",
    insuredName: "Retail Goods",
    lob: "Commercial Property",
    state: "FL",
    premium: 5500.75,
    dueDate: new Date(today.getTime() + 20 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    underwriter: "Alice Johnson",
    status: "New",
  },
  {
    id: "SUB-005",
    insuredName: "Data Systems",
    lob: "General Liability",
    state: "WA",
    premium: 15000.00,
    dueDate: new Date(today.getTime() + 15 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    underwriter: "Diana Prince",
    status: "Declined",
  },
  {
    id: "SUB-006",
    insuredName: "Manufacturing Co.",
    lob: "Workers Compensation",
    state: "IL",
    premium: 32000.00,
    dueDate: new Date(today.getTime() + 3 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    underwriter: "Charlie Brown",
    status: "Quoted",
  },
  {
    id: "SUB-007",
    insuredName: "Logistics Experts",
    lob: "Commercial Auto",
    state: "GA",
    premium: 11000.00,
    dueDate: subtractDays(today, 2).toISOString().split('T')[0],
    underwriter: "Bob Williams",
    status: "Overdue",
  },
  {
    id: "SUB-008",
    insuredName: "West Coast Realty",
    lob: "Commercial Property",
    state: "CA",
    premium: 18000.00,
    dueDate: new Date(today.getTime() + 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    underwriter: "Diana Prince",
    status: "New",
  },
  {
    id: "SUB-009",
    insuredName: "East Coast Fisheries",
    lob: "General Liability",
    state: "ME",
    premium: 9500.00,
    dueDate: new Date(today.getTime() + 25 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    underwriter: "Alice Johnson",
    status: "Bound",
  },
  {
    id: "SUB-010",
    insuredName: "Midwest Agriculture",
    lob: "Workers Compensation",
    state: "IA",
    premium: 19800.00,
    dueDate: new Date(today.getTime() + 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    underwriter: "Charlie Brown",
    status: "New",
  },
  {
    id: "SUB-011",
    insuredName: "Sunrise Hotels",
    lob: "Commercial Property",
    state: "NV",
    premium: 22000.00,
    dueDate: new Date(today.getTime() + 8 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    underwriter: "Diana Prince",
    status: "Quoted",
  },
  {
    id: "SUB-012",
    insuredName: "Software Architects",
    lob: "General Liability",
    state: "OR",
    premium: 7800.00,
    dueDate: new Date(today.getTime() + 12 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    underwriter: "Alice Johnson",
    status: "Bound",
  },
  {
    id: "SUB-013",
    insuredName: "National Transport",
    lob: "Commercial Auto",
    state: "AZ",
    premium: 14000.00,
    dueDate: new Date(today.getTime() + 18 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    underwriter: "Bob Williams",
    status: "New",
  },
  {
    id: "SUB-014",
    insuredName: "Five Star Restaurants",
    lob: "Workers Compensation",
    state: "NY",
    premium: 45000.00,
    dueDate: new Date(today.getTime() + 22 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    underwriter: "Charlie Brown",
    status: "Quoted",
  },
  {
    id: "SUB-015",
    insuredName: "Mountain Resorts",
    lob: "Commercial Property",
    state: "CO",
    premium: 31000.00,
    dueDate: subtractDays(today, 1).toISOString().split('T')[0],
    underwriter: "Diana Prince",
    status: "Overdue",
  },
];
